import re
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple

from langchain_ollama import OllamaEmbeddings, ChatOllama
from langchain_chroma import Chroma


# ============================================================
# CONFIGURATION
# ============================================================

OLLAMA_BASE_URL = "http://localhost:11434"

# MUST match the embedding model used by ingestion.py
EMBEDDING_MODEL = "mxbai-embed-large"

# Local text-generation model
CHAT_MODEL = "llama3.2:3b"

# MUST match ingestion.py
CHROMA_PERSIST_DIRECTORY = (
    Path(__file__).resolve().parent / "chroma_db"
)

COLLECTION_NAME = "documentation"

# Number of documents to retrieve from Chroma
TOP_K = 4

# ------------------------------------------------------------
# Stage 1: Semantic similarity threshold
#
# Based on your tests:
#
# Venkateswara  -> 0.5498  (documented)
# Balaji        -> 0.6847  (not explicitly documented)
# Kashi         -> 0.7397  (not documented)
# Biryani       -> 0.9365  (not documented)
#
# Chroma distance:
#     LOWER = more similar
# ------------------------------------------------------------

RELEVANCE_DISTANCE_THRESHOLD = 0.65

# ------------------------------------------------------------
# Stage 2: Evidence matching
#
# At least one meaningful query term must be found in the
# retrieved documentation.
#
# This prevents:
#
#     Balaji -> semantically similar to Tirumala
#     Kashi  -> semantically related to temple/pilgrimage
#
# from being accepted when those terms don't exist in the
# documentation.
# ------------------------------------------------------------

MIN_EVIDENCE_MATCHES = 1

# Maximum amount of documentation sent to the LLM
MAX_CONTEXT_CHARS = 12000

# Maximum number of tokens generated by the LLM
MAX_OUTPUT_TOKENS = 512

# Words that don't provide useful evidence
STOP_WORDS = {
    "a",
    "an",
    "the",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "to",
    "of",
    "in",
    "on",
    "at",
    "for",
    "from",
    "with",
    "about",
    "and",
    "or",
    "as",
    "by",
    "into",
    "how",
    "what",
    "when",
    "where",
    "why",
    "who",
    "which",
    "can",
    "could",
    "would",
    "should",
    "do",
    "does",
    "did",
    "give",
    "provide",
    "tell",
    "me",
    "more",
    "details",
    "detail",
    "information",
    "please",
}


# ============================================================
# INITIALIZE EMBEDDINGS
# ============================================================

embeddings = OllamaEmbeddings(
    model=EMBEDDING_MODEL,
    base_url=OLLAMA_BASE_URL,
)


# ============================================================
# INITIALIZE CHROMA
# ============================================================

vectorstore = Chroma(
    collection_name=COLLECTION_NAME,
    persist_directory=str(CHROMA_PERSIST_DIRECTORY),
    embedding_function=embeddings,
)


# ============================================================
# INITIALIZE LOCAL LLM
# ============================================================

model = ChatOllama(
    model=CHAT_MODEL,
    base_url=OLLAMA_BASE_URL,
    temperature=0,
    num_predict=MAX_OUTPUT_TOKENS,
)


# ============================================================
# TOKENIZATION / EVIDENCE HELPERS
# ============================================================

def extract_meaningful_terms(query: str) -> List[str]:
    """
    Extract meaningful words from the user's question.

    These terms are used as a second evidence check after
    semantic similarity retrieval.

    Example:

        "Provide more details about Venkateswara temple"

    becomes approximately:

        ["venkateswara", "temple"]
    """

    words = re.findall(r"[a-zA-Z0-9]+", query.lower())

    meaningful_terms = [
        word
        for word in words
        if len(word) >= 3 and word not in STOP_WORDS
    ]

    # Remove duplicates while preserving order
    return list(dict.fromkeys(meaningful_terms))


def find_evidence_matches(
    query: str,
    documents: List[Any],
) -> Tuple[List[str], List[str]]:
    """
    Check whether meaningful query terms actually occur
    in the retrieved documentation.

    Returns:
        matched_terms
        unmatched_terms
    """

    query_terms = extract_meaningful_terms(query)

    combined_text = " ".join(
        doc.page_content.lower()
        for doc in documents
    )

    matched_terms = []
    unmatched_terms = []

    for term in query_terms:

        if term in combined_text:
            matched_terms.append(term)
        else:
            unmatched_terms.append(term)

    return matched_terms, unmatched_terms


# ============================================================
# CHROMA RETRIEVAL
# ============================================================

def retrieve_documents(
    query: str,
) -> Tuple[List[Any], List[float]]:
    """
    Retrieve top-K documents from Chroma.

    Returns only documents that satisfy the semantic
    similarity threshold.
    """

    start_time = time.time()

    results = vectorstore.similarity_search_with_score(
        query,
        k=TOP_K,
    )

    retrieval_time = time.time() - start_time

    print(
        f"\nChroma retrieval time: "
        f"{retrieval_time:.2f} seconds"
    )

    print("\nRetrieved documents:")

    for i, (doc, distance) in enumerate(results, start=1):

        source = doc.metadata.get(
            "source",
            "Unknown",
        )

        print(
            f"  {i}. Distance: {distance:.4f} | "
            f"Source: {source}"
        )

    # --------------------------------------------------------
    # Stage 1: semantic similarity filter
    # --------------------------------------------------------

    relevant_results = [
        (doc, distance)
        for doc, distance in results
        if distance <= RELEVANCE_DISTANCE_THRESHOLD
    ]

    relevant_documents = [
        doc
        for doc, distance in relevant_results
    ]

    relevant_distances = [
        distance
        for doc, distance in relevant_results
    ]

    print(
        f"\nStage 1 - Semantic relevance: "
        f"{len(relevant_documents)}/{len(results)}"
    )

    return relevant_documents, relevant_distances


# ============================================================
# BUILD LLM CONTEXT
# ============================================================

def build_context(
    documents: List[Any],
) -> str:
    """
    Build a compact context for the LLM.

    The source is included so the model knows which document
    a piece of text came from, but Python—not the LLM—is
    responsible for the final source list.
    """

    context_parts = []
    current_length = 0

    for i, doc in enumerate(documents, start=1):

        source = doc.metadata.get(
            "source",
            "Unknown",
        )

        content = doc.page_content.strip()

        section = (
            f"--- DOCUMENT {i} ---\n"
            f"Source: {source}\n"
            f"Content:\n{content}\n"
        )

        if (
            current_length + len(section)
            > MAX_CONTEXT_CHARS
        ):

            remaining = (
                MAX_CONTEXT_CHARS
                - current_length
            )

            if remaining > 200:
                context_parts.append(
                    section[:remaining]
                )

            break

        context_parts.append(section)

        current_length += len(section)

    return "\n".join(context_parts)


# ============================================================
# BUILD UNIQUE SOURCE LIST
# ============================================================

def get_unique_sources(
    documents: List[Any],
) -> List[str]:
    """
    Return unique sources from retrieved documents.

    Multiple chunks can originate from the same source.
    """

    sources = []

    for doc in documents:

        source = doc.metadata.get(
            "source",
            "Unknown",
        )

        if source not in sources:
            sources.append(source)

    return sources


# ============================================================
# RUN RAG
# ============================================================

def run_llm(
    query: str,
) -> Dict[str, Any]:
    """
    Run strict documentation-grounded RAG.

    Pipeline:

        Query
          |
          v
        Chroma
          |
          v
        Semantic similarity gate
          |
          v
        Evidence/keyword gate
          |
          +---- NO ----> Return "not found"
          |
         YES
          |
          v
        Local LLM
          |
          v
        Documentation-only answer
    """

    print("\n" + "=" * 70)
    print(f"QUERY: {query}")
    print("=" * 70)

    # --------------------------------------------------------
    # STEP 1: Retrieve from Chroma
    # --------------------------------------------------------

    documents, distances = retrieve_documents(query)

    # --------------------------------------------------------
    # STEP 2: Semantic relevance gate
    # --------------------------------------------------------

    if not documents:

        print(
            "\nStage 1 FAILED:"
            "\nNo documents passed the semantic "
            "similarity threshold."
        )

        return {
            "answer": (
                "I don't have enough information in the "
                "available documentation to answer this question."
            ),
            "context": [],
            "sources": [],
            "distances": [],
        }

    # --------------------------------------------------------
    # STEP 3: Evidence matching
    # --------------------------------------------------------

    matched_terms, unmatched_terms = (
        find_evidence_matches(
            query,
            documents,
        )
    )

    print(
        "\nStage 2 - Evidence check"
    )

    print(
        f"Meaningful query terms: "
        f"{extract_meaningful_terms(query)}"
    )

    print(
        f"Matched terms: "
        f"{matched_terms}"
    )

    print(
        f"Unmatched terms: "
        f"{unmatched_terms}"
    )

    # --------------------------------------------------------
    # Require at least one meaningful term to exist
    # in the documentation.
    # --------------------------------------------------------

    if len(matched_terms) < MIN_EVIDENCE_MATCHES:

        print(
            "\nStage 2 FAILED:"
            "\nNo meaningful query terms were found "
            "in the retrieved documentation."
        )

        return {
            "answer": (
                "I don't have enough information in the "
                "available documentation to answer this question."
            ),
            "context": [],
            "sources": [],
            "distances": [],
        }

    print(
        "\nStage 2 PASSED:"
        "\nThe retrieved documentation contains "
        "evidence related to the query."
    )

    # --------------------------------------------------------
    # STEP 4: Build context
    # --------------------------------------------------------

    context = build_context(documents)

    print(
        f"\nContext sent to LLM: "
        f"{len(context):,} characters"
    )

    # --------------------------------------------------------
    # STEP 5: Strict closed-book prompt
    # --------------------------------------------------------

    prompt = f"""
You are a strict documentation assistant.

IMPORTANT RULES:

1. The supplied documentation is the ONLY source of truth.

2. Answer the user's question ONLY using information
   explicitly supported by the supplied documentation.

3. DO NOT use your pretrained knowledge.

4. DO NOT use general knowledge.

5. DO NOT add information from outside the documentation.

6. DO NOT infer or assume facts that are not supported
   by the documentation.

7. A topic being semantically related to the documentation
   does NOT mean that information about that topic exists
   in the documentation.

8. If the documentation does not contain enough information
   to answer the question, respond exactly:

"I don't have enough information in the available
documentation to answer this question."

9. Do not create or invent sources.

10. Do not mention a source as supporting an answer unless
    the supplied content from that source directly supports
    the answer.

DOCUMENTATION:

{context}

USER QUESTION:

{query}
"""

    # --------------------------------------------------------
    # STEP 6: Call local LLM
    # --------------------------------------------------------

    print(
        "\nCalling Ollama LLM..."
    )

    llm_start = time.time()

    response = model.invoke(prompt)

    llm_time = time.time() - llm_start

    print(
        f"LLM response time: "
        f"{llm_time:.2f} seconds"
    )

    answer = response.content

    # --------------------------------------------------------
    # STEP 7: Python-controlled sources
    # --------------------------------------------------------

    sources = get_unique_sources(documents)

    return {
        "answer": answer,
        "context": documents,
        "sources": sources,
        "distances": distances,
    }


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    query = input(
        "\nEnter your question: "
    ).strip()

    if not query:

        print(
            "Please enter a question."
        )

        raise SystemExit(1)

    result = run_llm(query)

    # --------------------------------------------------------
    # ANSWER
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("ANSWER")
    print("=" * 70)

    print(result["answer"])

    # --------------------------------------------------------
    # SOURCES
    # --------------------------------------------------------

    if result["sources"]:

        print("\n" + "=" * 70)
        print("SOURCES USED")
        print("=" * 70)

        for i, source in enumerate(
            result["sources"],
            start=1,
        ):
            print(f"{i}. {source}")

    else:

        print("\nNo documentation sources were used.")